[2020-08-09 19:01:00,901][WARNING] warning message
[2020-08-09 19:01:00,901][ERROR] error message
[2020-08-09 19:01:00,901][CRITICAL] critical message
[2020-08-09 19:01:00,901][ERROR] exception message
Traceback (most recent call last):
  File "C:/Users/syurskyi/PycharmProjects/TD/__syurskyi_repository__/maya/tutorials/Maya_Programming/CZ_Tutorials/013_Python_in_Production/31-python_in_production-logging_part_5/logger.py", line 103, in <module>
    b = a[0]
IndexError: list index out of range
