# c_ MyException E..
#     p__
#
# t__
#     r___ MyException("error")
# e___ E...
#     print('some exception')
# e_ ? a_ e
#     print ?
