import sys
try:
    raise IndexError
except:
    print(sys.exc_info())

# (<class 'IndexError'>, IndexError(), <traceback object at 0x019B8288>)

import traceback, sys

def grail():
    raise T  already got one

t__
    g.. arthur
e____
    e._i. = ___.e._i.
    print(e._i. 0
    print(e._i. 1
    tr__.print_tb e.._i. 2

# <class 'TypeError'>
# already got one
# File "<stdin>", line 2, in <module>
# File "<stdin>", line 2, in grail